# Generated by Django 5.1.4 on 2025-01-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubVariant',
            new_name='SubVarient',
        ),
        migrations.RenameModel(
            old_name='Variant',
            new_name='Varient',
        ),
    ]
